//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Purchase
    {
        public int Id { get; set; }
        public string Product { get; set; }
        public Nullable<int> IdStaff { get; set; }
        public int IdCategori { get; set; }
        public int Count { get; set; }
        public int Sum { get; set; }
        public Nullable<int> IdPursache { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Components Components { get; set; }
        public virtual Purchase Purchase { get; set; }
        public virtual Services Services { get; set; }
    }
}
