//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaleComponentsEntities1 : DbContext
    {
        public static SaleComponentsEntities1 _context;
        public SaleComponentsEntities1()
            : base("name=SaleComponentsEntities1")
        {
        }
        public static SaleComponentsEntities1 getContext()
        {

            if (_context == null)
                _context = new SaleComponentsEntities1();
            return _context;
        }


    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Components> Components { get; set; }
        public virtual DbSet<Compos_Congsign> Compos_Congsign { get; set; }
        public virtual DbSet<Counterparties> Counterparties { get; set; }
        public virtual DbSet<List_Purchase> List_Purchase { get; set; }
        public virtual DbSet<Privileges> Privileges { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Staffs> Staffs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Сonsignment> Сonsignment { get; set; }
    }
}
